version: '4'
services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./mongo-data:/data/db